---
title: "Fieller and Bootstrap Confidence Intervals"
format:
  html:
    embed-resources: true
    page-layout: full
---
```{r, echo=FALSE, message = FALSE, warning=FALSE}
source("./R/header.R")
load("./R/data_and_results/tables_and_plots.RData")
```

```{r, echo=FALSE}
#| label: tab-coverage-mar-large
df_ci_coverage %>%
     filter(condition == "mar_large") %>% 
     mutate(condition = "Setting: MAR") %>% 
     group_by(condition) %>%
     gt() %>%
     #tab_header(title = "Simulationsergebnisse", subtitle = "Vergleich der Konfidenzintervalle nach Bedingung") %>%
  cols_label(
    n_pc = "Nr. of factors",
    var_explained = "Prop. expl. var.",
    ci_boot_lower = "Lower",
    ci_boot_upper = "Upper",
    width_boot = "Width",
    coverage_boot = "Coverage (%)",
    ci_fieller_lower = "Lower",
    ci_fieller_upper = "Upper",
    width_fieller = "Width",
    coverage_fieller = "Coverage (%)",
    rmse = "RMSE",
    rrmse = "RRMSE"
  ) %>% 
     # Spalten-Gruppierung für mehr Übersicht (Spanning Headers)
     tab_spanner(label = "Bootstrap CI", columns = c(ci_boot_lower, ci_boot_upper, width_boot, coverage_boot)) %>%
     tab_spanner(label = "Fieller CI", columns = c(ci_fieller_lower, ci_fieller_upper, width_fieller, coverage_fieller)) %>%
     fmt_number(columns = where(is.numeric), decimals = 3) %>%
     tab_options(table.font.size = "small")
```
